---
version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "terraform"
    rebase-strategy: auto
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "UTC"
  - directory: /
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
